### ISSUE TITLE
www.redbeardlab.tech redirected you too many times.

### ISSUE THREAD

**Issue by manuelmeurer** [RedBeardLab/redbeardlab.github.io#4]
When I go to http://www.redbeardlab.tech/, I get:

The www.redbeardlab.tech page isn’t working
www.redbeardlab.tech redirected you too many times.
ERR_TOO_MANY_REDIRECTS

**Comment by siscia** [comment]
Well, weird, I just tried from my mobile and it seems to work...

I will investigate tomorrow morning...

How do you know about the domain though ? 

I haven't publicized it in any way, have I ?

-----Original Message-----

**Comment by manuelmeurer** [comment]
Now it works for me as well! :smile: 

I found it through http://stackshare.io/effe (click on "Visit Website")
